trigger:
  branches:
    include:
      - main

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: echo "Build $(Build.BuildNumber)"
            displayName: "Show Build Number"
          - script: echo "Running on $(System.StageName)"
            displayName: "Show Stage Name"
          - script: echo "Agent $(Agent.Name)"
            displayName: "Show Agent Info"