trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  simpleString: 'hello'
  simpleNumber: '42'
  buildConfig:
    debug: true
    release: false
  frameworks:
    - 'net6.0'
    - 'net8.0'

steps:
- script: echo "Test"
  displayName: 'Test step'
