# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Install SonarScanner for .NET
      run: |
        dotnet tool install --global dotnet-coverage
        dotnet tool install --global dotnet-sonarscanner
    - name: SonarScanner Begin
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}
        SONAR_HOST_URL: ${{ vars.SONAR_URL }}
        SONAR_ORGANIZATION: ${{ vars.SONAR_ORGANIZATION }}
      run: |
        args=()
        if [ -n "${{ env.SONAR_HOST_URL }}" ]; then
          args+=("/d:sonar.host.url=${{ env.SONAR_HOST_URL }}")
        fi
        if [ -n "${{ env.SONAR_ORGANIZATION }}" ]; then
          args+=("/o:${{ env.SONAR_ORGANIZATION }}")
        fi

        dotnet sonarscanner begin /d:sonar.token="${{ env.SONAR_TOKEN }}" /k:"${{ env.SONAR_PROJECT_KEY }}" ${args[@]} /d:sonar.cs.vscoveragexml.reportsPaths="TestResults/merged.vscoverage.xml" /d:sonar.projectBaseDir="$GITHUB_WORKSPACE" /d:sonar.exclusions="**/obj/**,**/bin/**,**/TestResults/**,.github/**,**/*.md" /d:sonar.coverage.exclusions="**/*.Tests/**,**/*.Samples/**"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test AdoPipelineTest.sln --no-build -c Release --filter "FullyQualifiedName~.UnitTests." --settings coverlet.runsettings --logger "console;verbosity=minimal" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Threshold=0
    - name: Merge coverage files
      run: |
        mkdir -p $GITHUB_WORKSPACE/TestResults
        dotnet-coverage merge "**/coverage.cobertura.xml" --output $GITHUB_WORKSPACE/TestResults/merged.vscoverage.xml --output-format xml
        dotnet-coverage merge "**/coverage.cobertura.xml" --output $GITHUB_WORKSPACE/TestResults/merged.cobertura.xml --output-format cobertura --verbosity detailed
    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-unit
        path: TestResults/merged.*.xml
        retention-days: 1
    - name: SonarScanner End
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet sonarscanner end /d:sonar.token="${{ env.SONAR_TOKEN }}"
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: TestResults/merged.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: code-coverage-results.md
    - name: Run sample tests
      run: dotnet test AdoPipelineTest.Samples -c Release --no-build --verbosity normal

  comment-pr:
    if: github.event_name == 'pull_request'
    needs: build
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: coverage-report
    - uses: marocchino/sticky-pull-request-comment@v2.9.4
      with:
        path: code-coverage-results.md
