name: Publish NuGet Package

permissions: 
  contents: read

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0'

      - name: Build
        run: |
          dotnet build --configuration Release
     
      - name: Run tests
        run: |
          dotnet test --configuration Release --no-build

      - name: Pack
        run: |
          dotnet pack --configuration Release -o ./artifacts
        
      - name: Configure GitHub Packages NuGet source
        run: |
          dotnet nuget add source --username blakharaz --password ${{ secrets.NUGET_PAT }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/blakharaz/index.json"


      - name: Publish to NuGet
        run: |
          dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_PAT }} --source "github" --skip-duplicate
